### ISSUE TITLE
Failed installation: MacOSX 10.10.5

### ISSUE THREAD

**Issue by deannachurch** [Illumina/hap.py#1]
I'm trying to install hap.py on my laptop and things went ok until the unit tests run. 
I ran this command:
```
python install.py ~/hap.py-install
```

This seems to be the relevant part of the message:
```
chrS:12-12 12-12:A . 0/1 0/1
chrS:13-13 13-13:C . 0/1 0/1
chrS:14-14 14-14:A 14-14:C 0/1 0/2 2/1
Unexpected variant calls: chrS:14-14 14-14:A 14-14:C 0/1 0/2 2/1
Assertion failed: (false), function test_method, file /Users/dchurch/Documents/source/hap.py/src/c++/test/test_allelesplit.cpp, line 197.
unknown location:0: fatal error in "testVariantPrimitiveSplitter": signal: SIGABRT (application abort requested)
/Users/dchurch/Documents/source/hap.py/src/c++/test/test_align.cpp:298: last checkpoint
```
and 
```
*** 1 failure detected in test suite "Master Test Suite"
Boost Unit tests FAILED!
Traceback (most recent call last):
  File "install.py", line 315, in <module>
    main()
  File "install.py", line 311, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 191, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /Users/dchurch/hap.py-install && /Users/dchurch/Documents/source/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1
```
Any help would be appreciated.

**Comment by pkrusche** [comment]
Did you use clang to compile [if so, which version?] ? I have seen subtle differences between clang and g++ that have produced similar errors.

It seems that on your system one of the genotypes comes out the other way around than the unit test expects. 

The expected result is

```
chrS:14-14 14-14:A 14-14:C 0/1 0/2 1/2
```

... but somehow it comes out as this:

```
chrS:14-14 14-14:A 14-14:C 0/1 0/2 2/1
```

... which the test code doesn't recognize as the same. I will fix the test in the next release. One workaround might be to try using g++ 4.9 from Macports rather than clang.

**Comment by pkrusche** [comment]
I have committed changes that should fix the issue to the dev branch, do these fix your issue?

**Comment by deannachurch** [comment]
Hi Peter-
I pulled the dev version and it fixed the problem I reported, but now the integration test failed:

```
Benchmarking Summary:
                 TRUTH.TOTAL  QUERY.TOTAL  METRIC.Recall  METRIC.Precision  METRIC.Frac_NA
Locations.INDEL          599          639       0.743633          0.910603        0.247261
Locations.SNP           3633         8889       0.994451          0.845682        0.523231
3225c3225,3226
< chr1	1547942	.	T	TC,TT	654.48	.	T_VT=INDEL;Q_VT=INDEL;T_LT=hetalt;Q_LT=het;type=FP;kind=alpartial;Regions=CONF	GT	2/1	0/1
---
> chr1	1547940	.	G	GT	0	.	T_VT=INDEL;Q_VT=NOCALL;T_LT=het;Q_LT=nocall;type=FN;kind=missing;Regions=CONF	GT	0/1	./.
> chr1	1547942	.	T	TC	654.48	.	T_VT=INDEL;Q_VT=INDEL;T_LT=het;Q_LT=het;type=TP;kind=match;Regions=CONF	GT	0/1	0/1
Performance output variants differ! vimdiff /var/folders/k6/_mb17_rx34z6l77xh_r79qm08s_jc4/T/happy.XXXXXXXXXX.UikTk2iQ.performance.vcf /Users/dchurch/Documents/source/hap.py/src/sh/../../example/integration/integrationtest.performance.vcf
Integration test FAILED!
Traceback (most recent call last):
  File "install.py", line 315, in <module>
    main()
  File "install.py", line 311, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 191, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /Users/dchurch/hap.py-install && /Users/dchurch/Documents/source/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1
```

I'm installing using python install script- should I try to build from source to control the compiler choice? It does look like it is compiling using clang:
```
[26Nov 09:08:39 l-mp-dchurch1 hap.py]$ clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

thanks so much for the quick help!

**Comment by pkrusche** [comment]
Thanks for trying the dev branch!

I think this is related to the same issue. Practically, I guess the numbers that come out of hap.py on this version of clang will differ only very slightly from results on gcc.

I try to push a fix for this on clang in the next weeks -- if this is not urgent, it might be worthwhile waiting until then.

If you would like to try compiling with gcc, here is a helpful script:

https://github.com/Illumina/hap.py/blob/master/configure.sh

It runs cmake and should be run in a build folder:

```
git clone https://github.com/Illumina/hap.py.git
cd hap.py
git checkout -b dev origin/dev
cd ..
mkdir hap.py-build
cd hap.py-build
# you can adjust these to point to the right places
CC=gcc
CXX=g++
BOOST_ROOT=...
../hap.py/configure.sh Release
make
export PYTHON=<python [virtualenv] with all packages needed for hap.py>
../hap.py/src/sh/run_tests.sh
```

**Comment by deannachurch** [comment]
Hi Peter- any chance the clang fix will be in soon? if not, I'll just build from scratch as you suggest.

**Comment by pkrusche** [comment]
Hi Deanna, I have looked into this, I think the problem comes from to using libc++ on the Mac vs. libstdc++ on Linux. I will try to see if I can get a Linux libc++ build to try this out. Unfortunately, switching to libstdc++ on the Mac seems to have issues also, so I wouldn't recommend that. 

Maybe running inside Docker would be a good temporary solution until there is a fix for this? There are now some instructions for running in a Docker image in #3 and in the dev branch.

**Comment by deannachurch** [comment]
Thanks for the info. It looks like we have hap.py running on our linux boxes, so I can just use that. I appreciate the quick responses.

**Comment by pkrusche** [comment]
I think I have fixed the problem and test cases in the latest dev branch (at least on Linux it now gives the same results with libc++ and libstdc++, which it didn't before). Could you perhaps give it a go? Thanks!

Note that this version of hap.py will give slightly different counts from 0.2.6 (mostly for het-alts) because this sorting change affects variant normalisation (in the default "partial-credit" mode hap.py splits het-alts before left-shifting, this fix might change their output order in some corner cases). 

If this works I'll release it with version 0.2.7.

**Comment by pkrusche** [comment]
Update: tests now working for me on OSX 10.11.1 with latest dev branch.

**Comment by deannachurch** [comment]
Success! I pulled the dev version and this is the result of running the python install script:
```
SUCCESS: Performance + consistency check (VCF).
Performance / Consistency test SUCCEEDED!
```

thanks!

**Comment by pkrusche** [comment]
Great, thanks for trying this out! I am aiming for a new release by next week or so, which will transfer these changes to master.
