### ISSUE TITLE
Very high memory usage in SGE

### ISSUE THREAD

**Issue by wangguangya60** [Illumina/hap.py#53]
Hi, this is the first time I use hap.py, and I use it in a SGE environment. Surprising, even with small variant files (about 40k variant positions from WES) as input, it costs a very high memory (upmost to nearly 50G). I'm not sure if I've used the right arguments.
`python hap.py 
     ref.snp.vcf.gz 
     sample.snp.vcf.gz 
     -o output 
     -f  region.bed 
     -r  hg19.fasta 
     --force-interactive`

And the SGE arguments are:
 `-l num_proc=4,vf=10G`

Any solution to this issue ? THANKS.

**Comment by pkrusche** [comment]
When not told otherwise, hap.py guesses the number of threads from the processors physically available, which can increase memory usage. SGE may allocate you 4 processors on a shared node, but the node might have more which hap.py may be trying to use. Can you try passing `--threads=4` to see if this fixes your issue?

**Comment by wangguangya60** [comment]
Hi, pkrusche. Yes, that works. Thanks a lot.

**Comment by pkrusche** [comment]
Happy to help!
