### ISSUE TITLE
Possible incorrect handling of incoherent VCFs

### ISSUE THREAD

**Issue by brendanofallon** [Illumina/hap.py#7]
Occasionally variant callers will produce output that is incoherent, but hap.py sometimes does not detect this type of error and can produce incorrect true positives. For instance, given input like:

Truth VCF: 
11    34133117    TTCCA        TACCA,T    1/2

Query VCF:
11    34133117    TTCCA        T    0/1
11    34133118    T            A    0/1

hap.py will proceed normally and emit a 'TP' result. However, the variants in the query VCF make conflicting assertions about the state of position 34133118 (the first variant asserts that it's ref + deleted, while the second asserts that it's ref + 'A'; they can't both be correct).  
 It seems that hap.py should produce at minimum a FP/ FN result for the above situation, or, even better, an error value of some sort indicating that the input was invalid.

**Comment by pkrusche** [comment]
This is a corner case where the design decision in hap.py is to be permissive in its interpretation of VCF variants. 

We interpret overlapping het calls as hemi since not all callers appear to write these in a consistent fashion (e.g. using ./1 or the <*> allele). 

I agree that it would be nice to have a way to flag these though. I would not label them as FP, but rather as inconsistent, and count them separately.
